---
author:
  - 'Ricardo SIGNES <rjbs@cpan.org>'
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mail-DeliveryStatus-BounceParser
no_index:
  directory:
    - inc
    - t
requires:
  MIME::Entity: 5.418
  perl: 5.00503
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/rjbs/mail-deliverystatus-bounceparser
version: 1.520
